"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['run.py']
DATA_FILES = ['parameter.py', 'gui.py', 'rkcmd.py', 'rkdeveloptool']
OPTIONS = {
    'iconfile': 'logo.icns'
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
